### ISSUE TITLE
Compatibility with Leaflet 1.x

### ISSUE THREAD

**Issue by DirkR** [ubergesundheit/Leaflet.EdgeMarker#12]
I'm using Leaflet.EdgeMarker in a map webapp and just wanted to update Leaftelt to v1.0.0-b2. Everything is working so far, except adding the EdgeMarker layer to the map.

The call

```javascript
L.edgeMarker({
    fillColor: 'yellow', color: 'green',
    radius: 15, fillOpacity: 0.3
}).addTo(map);
```
brings an TypeError:

```
TypeError: callback is undefined
Stack-Trace:
L.Map<.whenReady@leaflet/leaflet-src.js:4
.addLayer@leaflet/leaflet-src.js:3
L.EdgeMarker<.addTo@leaflet.edgemarker/Leaflet.EdgeMarker.js:44:7
...
```
What might be the problem?

**Comment by ubergesundheit** [comment]
Check out the newest commits in the gh-pages branch
