### ISSUE TITLE
Removing and EdgeMarker

### ISSUE THREAD

**Issue by lisaWriteJava** [ubergesundheit/Leaflet.EdgeMarker#13]
Hello,

Looking at the demo, it shows how this can be added to the map, but is how does a user remove it if they don't wish to see it. I've tried calling map.removeLayer(myEdgeMarker) but this doesn't work.

**Comment by ubergesundheit** [comment]
Hi,
I just added a function to remove the EdgeMarker from the map.
Just download the new Version and call `myEdgeMarker.destroy()`

**Comment by lisaWriteJava** [comment]
Thanks.
