### ISSUE TITLE
How to programmatically know if the EdgeMarker is on the map

### ISSUE THREAD

**Issue by lisaWriteJava** [ubergesundheit/Leaflet.EdgeMarker#14]
Is there a way to determine if the EdgeMarker is or is not added to the map before attempting to add or remove it.

**Comment by ubergesundheit** [comment]
The EdgeMarker adds a method `_getFeatures` to the `map`.

You could check against this method to determine if the EdgeMarkers are added to the map or not.

**Comment by lisaWriteJava** [comment]
wonderful. Thanks.
