### ISSUE TITLE
Limiting Markers

### ISSUE THREAD

**Issue by lisaWriteJava** [ubergesundheit/Leaflet.EdgeMarker#23]
Hello,

Is there a away to limit which markers the edgeMarkers point to. i have it pointing to anything on the map initially but I'd like limit it just those. When I plot something like a geoPopup, it also points to that which I don't want it to do or when I draw a new shape.

**Comment by ubergesundheit** [comment]
You could use the option `layerGroup` to specify the layer you want to create the edge markers for.

**Comment by lisaWriteJava** [comment]
Ok, thanks,
