### ISSUE TITLE
Hand pointer cursor on circlemarkers

### ISSUE THREAD

**Issue by mlegoff** [ubergesundheit/Leaflet.EdgeMarker#5]
Hello,

I notice that when we point a circlemarker, a hand pointer cursor appears but nothing happens when clicking.
I think it would be interesting to add to it, like going to the the marker position.

**Comment by ubergesundheit** [comment]
Nice Idea! If you have the time, please implement this and create a pull request. ;)

**Comment by ubergesundheit** [comment]
fixed in #6
