### ISSUE TITLE
Replace CircleMarker with Arrow icon ?

### ISSUE THREAD

**Issue by mlegoff** [ubergesundheit/Leaflet.EdgeMarker#7]
Hello,

I'd like to get your opinion about the CircleMaker. I think maybe a cardinal arrow pointing on the marker direction instead of a circlemarker would be relevant.

What do you think ?

**Comment by ubergesundheit** [comment]
Again, If you can code it up, I will happily accept pull requests ;)

**Comment by mlegoff** [comment]
Ok, i will work on it. Do you have an idea on how to make the arrow pointing on the marker's direction ? I'm new on the Jquery.

**Comment by ubergesundheit** [comment]
Please try to leave out any external dependencies! The direction should be computable through the vector direction from the map center to the marker.

**Comment by lutzer** [comment]
this code calculates the angle of the edgeMarkers:

```
_addEdgeMarkers: function () {

    ...
    
    // rotate markers    
    var centerX = mapPixelBounds.x/2;
    var centerY = mapPixelBounds.y/2;
    var angle = Math.atan2(centerY - y,centerX - x) / Math.PI * 180;
    newOptions.angle = angle;

    L.rotatedMarker(this._map.containerPointToLatLng([x,y]), newOptions)
                  .addTo(this._borderMarkerLayer);                 
}
```

The L.rotatedMarker class is taken from <https://github.com/bbecquet/Leaflet.PolylineDecorator>. The class lets you rotate an L.Marker object.

this code will create the L.RotatedMarker class:

```
L.RotatedMarker = L.Marker.extend({
    options: {
        angle: 0
    },

    _setPos: function (pos) {
        L.Marker.prototype._setPos.call(this, pos);
        
        if (L.DomUtil.TRANSFORM) {
            // use the CSS transform rule if available
            this._icon.style[L.DomUtil.TRANSFORM] += ' rotate(' + this.options.angle + 'deg)';
        } else if(L.Browser.ie) {
            // fallback for IE6, IE7, IE8
            var rad = this.options.angle * (Math.PI / 180),
                costheta = Math.cos(rad),
                sintheta = Math.sin(rad);
            this._icon.style.filter += ' progid:DXImageTransform.Microsoft.Matrix(sizingMethod=\'auto expand\', M11=' + 
                costheta + ', M12=' + (-sintheta) + ', M21=' + sintheta + ', M22=' + costheta + ')';                
        }
    }
});

L.rotatedMarker = function (pos, options) {
    return new L.RotatedMarker(pos, options);
};
```

**Comment by ubergesundheit** [comment]
Nice, seems you have figured it out. @lutzer will you create a pull request?

**Comment by lutzer** [comment]
i noticed that line 90: ` var mapPixelBounds = this._map.getSize();` can be deleted. that var is already assigned in line 69.
